name: KarKiller
main: top.karpvp.karfunction.karkiller.KarKiller
version: 1.1
author: listenstation
commands: 
  karkillermap:
    description: 没有权限
    permission: KarFunction.Karkiller.admin
    permission-message: 
    aliases: [kkm]